# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: matthewepler.github.io
email: matthewepler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Matthew Epler is a creative technologist whose work spans creative coding,
  physical computing, and design. http://mepler.com.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matthewepler.github.io" # the base hostname & protocol for your site
twitter_username: matthewepler
github_username:  matthewepler
homepage: mepler.com

# Build settings
markdown: kramdown
