# Site settings
title: I Have No Idea What I Am Doing
email: matthewepler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This is a place to document projects and process that consitute my blind and often misguided adventures in teknologeez. It is also my humble way of giving back to the communities that give freely of their time and talent for the benefit of idiots like me. As my dad would say, "I just don't want you to make the same mistakes I did." 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://matthewepler.github.io" # the base hostname & protocol for your site
url: "http://localhost:4000"
twitter_username: matthewepler
github_username:  matthewepler

# Build settings
markdown: kramdown
